<h1 class="page-header">Employee details</h1>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">        
        <table class="table table-striped table-hover">
            <tbody>
                <tr>
                    <td><label for="">Name</label></td>
                    <td><?php echo $employee["name"] ?></td>
                </tr>
                <tr>
                    <td><label for="">Email</label></td>
                    <td><?php echo $employee["email"] ?></td>
                </tr>
                <tr>
                    <td><label for="">Phone</label></td>
                    <td><?php echo $employee["phone"] ?></td>
                </tr>
                <tr>
                    <td><label for="">Address</label></td>
                    <td><?php echo $employee["address"] ?></td>
                </tr>
                <tr>
                    <td><label for="">Position</label></td>
                    <td><?php echo $employee["position"] ?></td>
                </tr>
                <tr>
                    <td><label for="">Salary</label></td>
                    <td><?php echo $employee["salary"] ?></td>
                </tr>
                <tr>
                    <td><label for="">Skills</label></td>
                    <td>
                        <?php foreach ($employee["skills"] as $skill) :?>
                            <?php echo $skill["skill"] ?><br />
                        <?php endforeach; ?>
                    </td>
                </tr>
            </tbody>
        </table>        
    </div>
</div>

<a href="<?php echo '/developers' ?>" class="btn btn-primary">Return to list</a>