<h1 class="page-header">Employee list</h1>

<form method="post">   
    <div class="row">
        <div class="form-group row">
            <label for="email" class="col-sm-1">Email</label>
            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                <input type="text" id="email" name="email" class="form-control" value="<?php echo $this->search; ?>">            
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">            
                <button type="submit" class="btn btn-primary">Submit</button>            
            </div>   
        </div>
    </div>    
</form>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Position</th>
                <th>Salary</th>
                <th>More</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($employees as $employee) :?>
                <tr>
                    <td><?php echo $employee["name"]?></td>
                    <td><?php echo $employee["email"]?></td>
                    <td><?php echo $employee["position"]?></td>
                    <td><?php echo $employee["salary"]?></td>
                    <td>
                        <a href="<?php echo '/developers/detail/' . $employee["id"] ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>